---

all:
  hosts:
    lb01:
      ansible_host: CHANGEME
    lb02:
      ansible_host: CHANGEME
    site:
      ansible_host: CHANGEME
    nginx:
      ansible_host: CHANGEME
  vars:
    ansible_connection_type: paramiko
    ansible_user: CHANGEME

balancer:
  hosts:
    lb01:
      ansible_host: CHANGEME
    lb02:
      ansible_host: CHANGEME
  vars:
    ansible_connection_type: paramiko
    ansible_user: CHANGEME
